id: PACA77A7C
initial_creation_type: input
source_metadata:
  title: Nubchen Sangye Yeshe
  language: bo
  description: 'Texts by and about Nubchen Sangye Yeshe (gnubs chen sangs rgyas ye
    shes), a major figure in the early Nyingma lineage:'
  volume:
    db87ecdc96274eb3a051a1d357d12528:
      title: Restorative Offering to the Eight Classes
      parent: Dharma Protectors
created_at: '2022-03-01T01:02:29.671809'
last_modified_at: '2022-03-01T01:02:29.671811'
